import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ReactQueryClientProvider } from "@/configs/provider/react-query-provider";
import { Toaster } from "@/components/ui/toaster";
import AuthRedirect from "@/configs/provider/authenticated";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        {/* <NextAuthClientProvider> */}
        {/* <AuthRedirect> */}
        <ReactQueryClientProvider>
          <Toaster />
          {children}
        </ReactQueryClientProvider>
        {/* </AuthRedirect> */}
        {/* </NextAuthClientProvider> */}
      </body>
    </html>
  );
}
